---
title: "pln_rmd"
output: html_document
date: "2023-10-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(PLNmodels)
library(ggplot2)
library(tidyverse)
library(googlesheets4)
```


```{r Am network data prep}

B_data <- read_csv("barplot_exports/level6_B.csv") %>%
  rename(id = index)
View(B_data)

C_data <- read_csv("barplot_exports/level6_C.csv") %>%
  rename(id = index)
View(C_data)

D_data <- read_csv("barplot_exports/level6_D.csv") %>%
  rename(id = index)
View(D_data)

#abundance<-read_sheet("https://docs.google.com/spreadsheets/d/120PG7RZufx3aKSijSOKWAMKIstlERbL9ryG98aCj4RM/edit?usp=sharing", sheet = "sum_prev_top50_tp", col_names = TRUE) %>%
 # rename(id = index)
#metadata <- read_csv("metadata_test.csv")
#joined_data <- inner_join(abundance, metadata, by = "id")

C_metadata_ordered <- C_data %>%
  select(id,location,sex,rp)


C_abundance_ordered_a <- C_data %>%
  select(-id) %>%
  select(!`barcode-sequence`:indexing) %>%
  select(ends_with(';__')) %>%
  rename_with(~sub('.*;.__(.*);__','\\1', .))

C_abundance_ordered_b <- C_data %>%
  select(-id) %>%
  select(!`barcode-sequence`:indexing) %>%
  select(matches('[a-z]$')) %>%
  rename_with(~sub('.*__(.*$)','\\1', .))

C_abundance_ordered <- cbind(C_abundance_ordered_a,C_abundance_ordered_b) 
```
```{r Am network analysis}
#Check to make sure this doesn't include id in abundance matrix.
C_microbiome <- prepare_data(C_abundance_ordered, C_metadata_ordered, offset = "GMPR")

str(C_microbiome)
View(C_microbiome)

plot.new()
corrplot::corrplot(
  t(log(1 + C_abundance_ordered)),
  is.corr = FALSE,
  addgrid.col = NA, 
  tl.cex = 0.5, 
)

myPLN <- PLN(Abundance ~ 1, C_microbiome)
myPLN
c(myPLN$loglik, myPLN$BIC, myPLN$ICL)

data.frame(
  fitted   = as.vector(fitted(myPLN)),
  observed = as.vector(C_microbiome$Abundance)
) %>% 
  ggplot(aes(x = observed, y = fitted)) + 
    geom_point(size = .5, alpha =.25 ) + 
    scale_x_log10() + 
    scale_y_log10() + 
    theme_bw() + annotation_logticks()

myPLN %>% sigma() %>% cov2cor() %>% corrplot::corrplot()

myPLN_weighted <-
  PLN(
    Abundance ~ 1,
    data    = C_microbiome,
    weights = runif(nrow(C_microbiome)),
    control = PLN_param(trace = 0)
  )
data.frame(
  unweighted = as.vector(fitted(myPLN)),
  weighted   = as.vector(fitted(myPLN_weighted))
) %>%
  ggplot(aes(x = unweighted, y = weighted)) +
    geom_point(size = .5, alpha =.25 ) +
    scale_x_log10() +
    scale_y_log10() +
    theme_bw() + annotation_logticks()

myPLN_offsets <- 
  PLN(Abundance ~ 1 + offset(log(Offset)), 
      data = C_microbiome, control = PLN_param(trace = 0))

rbind(
  myPLN$criteria,
  myPLN_offsets$criteria
) %>% knitr::kable()

myPLN_diagonal <-
  PLN(
    Abundance ~ 1 + offset(log(Offset)),
    data = C_microbiome, control = PLN_param(covariance = "diagonal", trace = 0)
  )

myPLN_spherical <-
  PLN(
    Abundance ~ 1 + offset(log(Offset)),
    data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0)
  )

myPLN_default <-
  PLN(
    Abundance ~ 1 + offset(log(Offset)),
    data = C_microbiome,
  )

myPLN_full <-
  PLN(
    Abundance ~ 1 + offset(log(Offset)),
    data = C_microbiome, control = PLN_param(covariance = "full", trace = 0)
  )

rbind(
  myPLN_offsets$criteria,
  myPLN_diagonal$criteria,
  myPLN_spherical$criteria,
  myPLN_default$criteria,
  myPLN_full$criteria
) %>%
  as.data.frame(row.names = c("offsets","diagonal", "spherical", "full", "default")) %>%
  knitr::kable()

myPLN_loc_sph <- PLN(Abundance ~ 1 + location + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_sex_sph <- PLN(Abundance ~ 1 + sex + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_rp_sph <- PLN(Abundance ~ 1 + rp + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_loc_sex_sph <- PLN(Abundance ~ 1 + sex + location + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_loc_rp_sph <- PLN(Abundance ~ 1 + location + rp + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_sex_rp_sph <- PLN(Abundance ~ 1 + sex + rp + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))
myPLN_loc_sex_rp_sph <- PLN(Abundance ~ 1 + rp + sex + location + offset(log(Offset)), data = C_microbiome, control = PLN_param(covariance = "spherical", trace = 0))

rbind(
  myPLN_offsets$criteria,
  myPLN_diagonal$criteria,
  myPLN_spherical$criteria,
  myPLN_default$criteria,
  myPLN_full$criteria,
  myPLN_loc_sph$criteria,
  myPLN_sex_sph$criteria,
  myPLN_rp_sph$criteria,
  myPLN_loc_sex_sph$criteria,
  myPLN_loc_rp_sph$criteria,
  myPLN_sex_rp_sph$criteria,
  myPLN_loc_sex_rp_sph$criteria 
) %>%
  as.data.frame(row.names = c("offsets","diagonal", "spherical", "default", "full", "loc_sph", "sex_sph", "rp_sph", "loc_sex_sph", "loc_rp_sph", "sex_rp_sph", "loc_sex_rp_sph")) %>%
  knitr::kable()
```
```{r PLN-LDA}
myLDA_nocov <- PLNLDA(Abundance ~ 0 + offset(log(Offset)),
                      grouping = rp, 
                      data = C_microbiome)

myLDA_nocov
sigma(myLDA_nocov) %>% corrplot::corrplot(is.corr = FALSE)
coef(myLDA_nocov)
myLDA_nocov$group_means %>% head() %>% knitr::kable(digits = 2)


myLDA_loc <- PLNLDA(Abundance ~ location + 0 + offset(log(Offset)),
                   grouping = rp,
                   data = C_microbiome)

myLDA_loc
sigma(myLDA_loc) %>% corrplot::corrplot(is.corr = FALSE)
coef(myLDA_loc)
myLDA_nocov$group_means %>% head() %>% knitr::kable(digits = 2)




plot(myLDA_nocov)
```
```{r PCA}
PCA_models <- PLNPCA(
  Abundance ~ 1 + offset(log(Offset)),
  data  = C_microbiome, 
  ranks = 1:30
)

PCA_models$criteria %>% knitr::kable()
PCA_models$convergence  %>% knitr::kable()

plot(PCA_models)


myPCA_ICL <- getBestModel(PCA_models, "ICL") 
myPCA_BIC <- getModel(PCA_models, 3) # getBestModel(PCA_models, "BIC")  is equivalent here 


plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$location, plot = TRUE, main = "", )





pdf("PCA_BIC_individuals.pdf", width = 6, height = 6)
gridExtra::grid.arrange(
  plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$location, plot = FALSE, main = ""),
  plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$sex, plot = FALSE, main = "individual factor"),
  plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$rp, plot = FALSE, main = ""),
  plot(myPCA_BIC, map = "variable", plot = FALSE),
  ncol = 2
)
dev.off()

pdf("PCA_BIC_variable.pdf", width = 4.5, height = 4.5)
gridExtra::grid.arrange(
  plot(myPCA_BIC, map = "variable", plot = FALSE),
  ncol = 1
)
dev.off()

pdf("PCA_BIC_location.pdf", width = 9, height = 4.5)
gridExtra::grid.arrange(
  plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$location, plot = FALSE),
  plot(myPCA_BIC, map = "variable", plot = FALSE),
  ncol = 2
)
dev.off()

pdf("PCA_BIC_rp.pdf", width = 9, height = 4.5)
gridExtra::grid.arrange(
  plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$rp, plot = FALSE),
  plot(myPCA_BIC, map = "variable", plot = FALSE),
  ncol = 2
)
dev.off()


plot(myPCA_BIC, ind_cols = C_microbiome$rp)


```

```{r network models}

network_models <- PLNnetwork(Abundance ~ 1 + offset(log(Offset)),
                             data = C_microbiome
)

network_models

network_models$criteria %>% head() %>% knitr::kable()

network_models$convergence %>% head() %>% knitr::kable()

plot(network_models, "diagnostic")

plot(network_models)

coefficient_path(network_models, corr = TRUE) %>% 
  ggplot(aes(x = Penalty, y = Coeff, group = Edge, colour = Edge)) + 
  geom_line(show.legend = FALSE) +  coord_trans(x="log10") + theme_bw()

model_pen <- getModel(network_models, network_models$penalties[20]) # give some sparsity
model_BIC <- getBestModel(network_models, "BIC")   # if no criteria is specified, the best BIC is used
model_BIC

library(future)
plan(multisession, workers = 2)

n <- nrow(C_microbiome)
subs <- replicate(10, sample.int(n, size = n/2), simplify = FALSE)
stability_selection(network_models, subsamples = subs)

model_StARS <- getBestModel(network_models, "StARS")

plot(network_models, "stability")

future::plan("sequential")

model_StARS

my_graph <- plot(model_StARS, plot = FALSE)
my_graph

plot(model_StARS)
plot(model_StARS, type = "support", output = "corrplot")

data.frame(
  fitted   = as.vector(fitted(model_StARS)),
  observed = as.vector(C_microbiome$Abundance)
) %>% 
  ggplot(aes(x = observed, y = fitted)) + 
    geom_point(size = .5, alpha =.25 ) + 
    scale_x_log10(limits = c(1,1000)) + 
    scale_y_log10(limits = c(1,1000)) + 
    theme_bw() + annotation_logticks()
```

```{r trichoptera vignette}

data("trichoptera")

trichoptera <- prepare_data(trichoptera$Abundance, trichoptera$Covariate)

str(trichoptera)
View(trichoptera)

corrplot::corrplot(
  t(log(1 + trichoptera$Abundance)),
  is.corr = FALSE,
  addgrid.col = NA
)

network_models <- PLNnetwork(Abundance ~ 1 + offset(log(Offset)), data = trichoptera)

network_models

network_models$criteria %>% head() %>% knitr::kable()

network_models$convergence %>% head() %>% knitr::kable()

plot(network_models, "diagnostic")

plot(network_models)

coefficient_path(network_models, corr = TRUE) %>% 
  ggplot(aes(x = Penalty, y = Coeff, group = Edge, colour = Edge)) + 
  geom_line(show.legend = FALSE) +  coord_trans(x="log10") + theme_bw()

model_pen <- getModel(network_models, network_models$penalties[20]) # give some sparsity
model_BIC <- getBestModel(network_models, "BIC")   # if no criteria is specified, the best BIC is used

library(future)
plan(multisession, workers = 2)

n <- nrow(trichoptera)
subs <- replicate(10, sample.int(n, size = n/2), simplify = FALSE)
stability_selection(network_models, subsamples = subs)

model_StARS <- getBestModel(network_models, "StARS")

plot(network_models, "stability")

future::plan("sequential")

model_StARS

my_graph <- plot(model_StARS, plot = FALSE)
my_graph

plot(model_StARS)
```
plot(myPCA_BIC, map = "individual", ind_cols = C_microbiome$location, plot = TRUE, main = "")
